default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL_TEST", ENV["DATABASE_URL"]&.sub(/development/, "test") || "postgresql://postgres:foaf_dev_password@db:5432/foaf_protocol_test") %>

production:
  <<: *default
